name: angle
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.4

# Add regular dependencies here.
dependencies:
  range:
    git:
      url: https://github.com/grogersstephen/range.dart.git
      ref: main

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
